# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCzd5GkCrreJLV0Af6yT1JRyNVtq2PlV
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set page title
st.set_page_config(page_title="Kaduna GPI Dashboard", layout="wide")
st.title("📊 Kaduna Gender Parity Index Analysis")

# --- DATA LOADING ---
@st.cache_data
def load_data():
    # Load and clean data based on your notebook logic
    data = pd.read_excel('GPI data_main.xlsx')
    data.columns = data.columns.str.strip()
    data['LGA'] = data['LGA'].str.upper().str.strip()

    lga_mapping = {
        'BIRNINGWARI': 'BIRNIN GWARI',
        'K NORTH': 'KADUNA NORTH',
        'K SOUTH': 'KADUNA SOUTH',
        'S GARI': 'SABON GARI',
        'Z KATAF': 'ZANGON KATAF',
        'ZANGONKATAF': 'ZANGON KATAF'
    }
    data['LGA'] = data['LGA'].replace(lga_mapping)
    return data

try:
    df = load_data()

    # --- SIDEBAR FILTERS ---
    st.sidebar.header("Filter Data")
    selected_year = st.sidebar.selectbox("Select Academic Year", options=df['Year'].unique())
    selected_lga = st.sidebar.multiselect("Select LGAs", options=df['LGA'].unique(), default=df['LGA'].unique()[:5])

    # Filter dataframe
    filtered_df = df[(df['Year'] == selected_year) & (df['LGA'].isin(selected_lga))]

    # --- KEY METRICS ---
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Schools", int(filtered_df['total number of schools'].sum()))
    col2.metric("Total Pupils", int(filtered_df['total number of pupils'].sum()))
    col3.metric("Avg GPI", round(filtered_df['GPI'].mean(), 2))

    # --- VISUALIZATIONS ---
    st.subheader(f"Gender Parity Index by LGA ({selected_year})")

    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(data=filtered_df, x='LGA', y='GPI', ax=ax, palette="viridis")
    plt.xticks(rotation=45)
    st.pyplot(fig)

    # Show Data Table
    if st.checkbox("Show raw data"):
        st.write(filtered_df)

except FileNotFoundError:
    st.error("Please upload 'GPI data.xlsx' to the repository.")
